sudo: required

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq beanstalkd
 - sudo beanstalkd -d -l 127.0.0.1 -p 11300

language: node_js

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x
  - SENECA_VER=@3.x.x

node_js:
 - 4
 - 6

after_script:
 - npm run coveralls
